### PR TITLE
Edunext utec/shibolleth

### PR DESCRIPTION
**Pull request by felipemontoya**
This are the custom-code migrations to eucalyptus

@diegomillan

### CODE REVIEW

**Comment by felipemontoya** [comment]
@diegomillan just waiting for your internal test to go through

**Comment by diegomillan** [comment]
I think we are ready to merge @felipemontoya

**Comment by felipemontoya** [comment]
@diegomillan you mentioned some changes that you added later. Are those here or at the theme repository?

**Comment by diegomillan** [comment]
@felipemontoya yes, I squashed and pushed those  extra changes

**Pull request merged**
